# Generated by Django 5.2.10 on 2026-02-02 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_book_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('engine_type', models.CharField(choices=[('openai', 'OpenAI GPT'), ('collaborative', 'Collaborative Filtering'), ('content', 'Content-Based'), ('hybrid', 'Hybrid')], default='openai', max_length=20)),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('max_recommendations', models.PositiveIntegerField(default=5)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key_configured', models.BooleanField(default=False)),
                ('purchase_weight', models.FloatField(default=0.4)),
                ('review_weight', models.FloatField(default=0.3)),
                ('browse_weight', models.FloatField(default=0.2)),
                ('wishlist_weight', models.FloatField(default=0.1)),
            ],
            options={
                'verbose_name': 'Recommendation Engine',
                'verbose_name_plural': 'Recommendation Engines',
                'db_table': 'recommendation_engine',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_history', models.JSONField(default=dict)),
                ('recommended_list', models.JSONField(default=list)),
                ('ai_prompt', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='store.customer')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='store.recommendationengine')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('like', 'Liked'), ('dislike', 'Disliked'), ('not_interested', 'Not Interested'), ('already_read', 'Already Read'), ('will_buy', 'Will Buy Later')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to='store.customer')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='store.recommendation')),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedbacks',
                'db_table': 'recommendation_feedback',
                'unique_together': {('recommendation', 'customer', 'book')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_purchased', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_items', to='store.book')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.recommendation')),
            ],
            options={
                'verbose_name': 'Recommendation Item',
                'verbose_name_plural': 'Recommendation Items',
                'db_table': 'recommendation_item',
                'ordering': ['rank'],
                'unique_together': {('recommendation', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('behavior_type', models.CharField(choices=[('view', 'Viewed Book'), ('search', 'Searched'), ('add_cart', 'Added to Cart'), ('purchase', 'Purchased'), ('review', 'Reviewed'), ('wishlist', 'Added to Wishlist'), ('remove_cart', 'Removed from Cart')], max_length=20)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_behaviors', to='store.book')),
                ('category_viewed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='store.customer')),
            ],
            options={
                'verbose_name': 'User Behavior',
                'verbose_name_plural': 'User Behaviors',
                'db_table': 'user_behavior',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'behavior_type'], name='user_behavi_custome_d5ec32_idx'), models.Index(fields=['book', 'behavior_type'], name='user_behavi_book_id_7f6337_idx')],
            },
        ),
    ]
