# Generated by Django 5.1.5 on 2026-03-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('shipping_method_id', models.IntegerField()),
                ('shipping_method_name', models.CharField(blank=True, max_length=100)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method_id', models.IntegerField()),
                ('payment_method_name', models.CharField(blank=True, max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang vận chuyển'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('shipping_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(default='book', max_length=50)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_subtitle', models.CharField(blank=True, max_length=255)),
                ('product_image_url', models.URLField(blank=True)),
                ('product_snapshot', models.JSONField(blank=True, default=dict)),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('book_title', models.CharField(blank=True, max_length=255)),
                ('book_author', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
