# Generated by Django 5.2.12 on 2026-04-13 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('search', 'Search'), ('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add To Cart'), ('purchase', 'Purchase'), ('chat', 'Chat')], db_index=True, max_length=30)),
                ('service_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('product_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('query_text', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=120)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='customer_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='product_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='service_type',
            field=models.CharField(db_index=True, default='book', max_length=50),
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('user', 'User'), ('product', 'Product'), ('category', 'Category'), ('query', 'Query')], db_index=True, max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('label', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('node_type', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=60)),
                ('service_type', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'service_type'], name='recommender_source_86055f_idx')],
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(db_index=True, max_length=50)),
                ('weight', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='recommender.graphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='recommender.graphnode')),
            ],
            options={
                'indexes': [models.Index(fields=['relation', 'weight'], name='recommender_relatio_2e7837_idx')],
                'unique_together': {('source', 'target', 'relation')},
            },
        ),
    ]
