# Generated by Django 5.2.12 on 2026-04-06 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('book', 'Book'), ('cloth', 'Cloth'), ('laptop', 'Laptop'), ('mobile', 'Mobile')], default='book', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('name', 'product_type')},
            },
        ),
    ]
